# ===================================================================
# Humano mutante mercado libre
# autor: angel marin
# ===================================================================

server:
  port: 8080

spring:
  data:
    mongodb:
      #uri: mongodb://localhost:27017
      uri: mongodb+srv://appmovil:gwZTLQgPvJAD3Ds5@cluster0.ung5a.mongodb.net/?retryWrites=true&w=majority
      user:
      repositories:
        type: AUTO
      database: meli

logging:
  level:
    root: INFO
    com.meli.mutant: DEBUG
    org.springframework.integration: info
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
